name: Build and Test

on:
  pull_request:
      branches:
      - 'main'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      - name: Build
        run: go build -v ./...
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.59.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      # - name: Test
      #   run: go test -v ./...