name: build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code to a GOPATH compatible directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/sol-eng/wbi
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Build
        run: go build -v ./...
        env:
          GOPATH: /home/runner/work/wbi/go
      # - name: Test
      #   run: go test -v ./...
      #  env:
      #    GOPATH: /home/runner/work/wbi/go

  goreleaser:
    needs: code-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}